#!/usr/bin/env bash

AGENTS_WORKFLOW_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

bash "$AGENTS_WORKFLOW_DIR/common-pre-setup"
if command -v get-task >/dev/null; then
  while IFS= read -r line; do
    export "$line"
  done < <(get-task --get-setup-env)
fi

if [ -f .agents/copilot-setup ]; then
  .agents/copilot-setup
fi

if [ -f .agents/common-post-setup ]; then
  .agents/common-post-setup
fi

bash "$AGENTS_WORKFLOW_DIR/common-post-setup"
