#!/usr/bin/env bash

echo "Executing Codex Setup"

apt-get update
apt-get install -y --no-install-recommends \
  git \
  fossil \
  mercurial \
  just \
  ruby-full \
  zfsutils-linux \
  btrfs-progs

sudo gem install rubocop
